# Generated by Django 6.0.1 on 2026-03-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productcolor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.product'),
        ),
    ]
