# Generated by Django 6.0.1 on 2026-03-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_is_featured_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(default='Phân loại', max_length=50),
        ),
    ]
