# Generated by Django 6.0.1 on 2026-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_variant_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
    ]
