# Generated by Django 6.0.1 on 2026-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productcolor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/video_thumb/'),
        ),
    ]
